### ISSUE TITLE
罗哥好，小弟想请教下，我用的你的这个框架，如何能兼容ie8

### ISSUE THREAD

**Issue by wangjunwei910208** [javaLuo/react-luo#10]
我按网上给的例子，降了react的版本，也删除了antd等等，但依然兼容不了ie8，求助

**Comment by javaLuo** [comment]
React, React-Router，还有其他一些npm包也不支持IE8
兼容IE8需要很多垫片库
放弃IE8吧...

**Comment by zhans1993** [comment]
luo 哥知道可以ie8 兼容的webscoket 包么，或者其他替代实现方法，请教一下

**Comment by javaLuo** [comment]
@zhans1993 不是很了解了，git上搜了一下有些封装的websocket，不知道能不能兼容ie8

**Comment by yangzhGit** [comment]
兼容ie8可以看下司徒正美大神的anujs

**Comment by javaLuo** [comment]
@yangzhGit 好的!
