### ISSUE TITLE
luo哥，怎么按需加载打包后的js代码啊？急求

### ISSUE THREAD

**Issue by wangjunwei910208** [javaLuo/react-luo#11]
现在项目放到外网服务器之后，页面加载出来太慢，不知道怎么解决了

**Comment by javaLuo** [comment]
可以用react-loadble (https://github.com/jamiebuilds/react-loadable)
专门用来做懒加载的。你把那些比较重量级的路由页面都配置一下，打包后就自动按需加载了。

**Comment by wangjunwei910208** [comment]
我安装bundle-loader，按网上常用教程如：http://blog.csdn.net/qq_38054239/article/details/78844844  配置后，为啥Bundle.js一直报错啊

**Comment by javaLuo** [comment]
你肯定哪里没写对吧
https://github.com/javaLuo/react-luo/tree/react-luo-webpack
这个里面我就是用bundle-loader配的代码分割，可以参考一下
