### ISSUE TITLE
react+redux框架配置从无到有直到正常运行全流程 

### ISSUE THREAD

**Issue by yangzhGit** [javaLuo/react-luo#17]
能不能根据目前最新的库和流程更新下？？？
十分感谢！！！

**Comment by javaLuo** [comment]
没问题。接下来就着手干这件事

**Comment by javaLuo** [comment]
https://blog.csdn.net/lx376693576/article/details/79715268

写得比较简陋

**Comment by weiqiujuan** [comment]
在使用的时候出错了
