### ISSUE TITLE
可以加入dll打包吗

### ISSUE THREAD

**Issue by zy19940510** [javaLuo/react-luo#18]
目前用的你这个脚手架在做东西，但是每次代码变化重新编译打包就要等很久，可以优化一下吗

**Comment by javaLuo** [comment]
没问题

**Comment by javaLuo** [comment]
抱歉，我一直在关注autodll-webpack-plugin这个插件
https://github.com/asfktz/autodll-webpack-plugin/pull/106
webpack4之后，作者貌似还没有升级完毕。
如果用官方原版的dllPlugin，没办法把dll.js正确的引入index.html（开发环境的index.html是在内存中存在，并不会真的生成）。而且每次都需要手动打包dll.js
我会持续关注autodll-webpack-plugin，直到作者把他升级完毕
所以目前...暂时用不了 - -

**Comment by zy19940510** [comment]
你好，我已经用自带dll实现了
    
        
            
                
                    
                        
                    
                    
                        
                            张宇
                            
                            
                                
                                    邮箱：nicejerry666@gmail.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
            在2018年04月24日 18:06，Logic 写道： 抱歉，我一直在关注autodll-webpack-plugin这个插件
asfktz/autodll-webpack-plugin#106
webpack4之后，作者貌似还没有升级完毕。
如果用官方原版的dllPlugin，没办法把dll.js正确的引入index.html（开发环境的index.html是在内存中存在，并不会真的生成）。而且每次都需要手动打包dll.js
我会持续关注autodll-webpack-plugin，直到作者把他升级完毕
所以目前...暂时用不了 - -

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/javaLuo/react-luo","title":"javaLuo/react-luo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/javaLuo/react-luo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@javaLuo in #18: 抱歉，我一直在关注autodll-webpack-plugin这个插件\r\nhttps://github.com/asfktz/autodll-webpack-plugin/pull/106\r\nwebpack4之后，作者貌似还没有升级完毕。\r\n如果用官方原版的dllPlugin，没办法把dll.js正确的引入index.html（开发环境的index.html是在内存中存在，并不会真的生成）。而且每次都需要手动打包dll.js\r\n我会持续关注autodll-webpack-plugin，直到作者把他升级完毕\r\n所以目前...暂时用不了 - -\r\n"}],"action":{"name":"View Issue","url":"https://github.com/javaLuo/react-luo/issues/18#issuecomment-383877271"}}}

**Comment by zy19940510** [comment]
因为内存中的html是用public里的html复制过来的，可以在public里的html手动引入script标签，我的目录是assets/lib.js
    
        
            
                
                    
                        
                    
                    
                        
                            张宇
                            
                            
                                
                                    邮箱：nicejerry666@gmail.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
            在2018年04月24日 18:06，Logic 写道： 抱歉，我一直在关注autodll-webpack-plugin这个插件
asfktz/autodll-webpack-plugin#106
webpack4之后，作者貌似还没有升级完毕。
如果用官方原版的dllPlugin，没办法把dll.js正确的引入index.html（开发环境的index.html是在内存中存在，并不会真的生成）。而且每次都需要手动打包dll.js
我会持续关注autodll-webpack-plugin，直到作者把他升级完毕
所以目前...暂时用不了 - -

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/javaLuo/react-luo","title":"javaLuo/react-luo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/javaLuo/react-luo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@javaLuo in #18: 抱歉，我一直在关注autodll-webpack-plugin这个插件\r\nhttps://github.com/asfktz/autodll-webpack-plugin/pull/106\r\nwebpack4之后，作者貌似还没有升级完毕。\r\n如果用官方原版的dllPlugin，没办法把dll.js正确的引入index.html（开发环境的index.html是在内存中存在，并不会真的生成）。而且每次都需要手动打包dll.js\r\n我会持续关注autodll-webpack-plugin，直到作者把他升级完毕\r\n所以目前...暂时用不了 - -\r\n"}],"action":{"name":"View Issue","url":"https://github.com/javaLuo/react-luo/issues/18#issuecomment-383877271"}}}

**Comment by javaLuo** [comment]
好的！学习了
