### ISSUE TITLE
在线主题切换

### ISSUE THREAD

**Issue by zhans1993** [javaLuo/react-luo#19]
luo哥,我现在需要做一个功能 ：程序提供多套主题模板，用户可以在线切换主题，这样的功能应该怎么做呢，有思路可以参考一下么？多谢！！！

**Comment by javaLuo** [comment]
需要自己编写不同主题的CSS文件
http://ant-design.gitee.io/docs/react/customize-theme-cn
antd提供了很多全局CSS变量，就根据这个自定义自己的主题。
程序中就可以选择加载不同的CSS来切换主题
