### ISSUE TITLE
引用相对路径图片 报错

### ISSUE THREAD

**Issue by Just-focus** [javaLuo/react-luo#29]
Module not found: Error: Can't resolve 'img/1.png' in '/Users/chenxiaogang/workspace/hupu/games_frontend/offline_react/src/container/bbs/admire/admire_1'

**Comment by javaLuo** [comment]
import Img from "./img/1.png"; 这样呢

**Comment by Just-focus** [comment]
但是我是打算在背景里面写的。。写绝对路劲就可以

**Comment by Just-focus** [comment]
但是写绝对路劲就不会编译了

**Comment by Just-focus** [comment]
嗯嗯。。可以了。。谢谢
