### ISSUE TITLE
您好，我想再次请教个问题，麻烦了

### ISSUE THREAD

**Issue by wangjunwei910208** [javaLuo/react-luo#3]
export const editProblem=(obj)=>{
	Fetchapi.newPost(
    	'url',obj
	).then(
	    msg => {
			console.log(msg);
			dispatch(xxxAction);
	    }
	).catch(() => {
	    message.error('网络错误，请重试');
	});
}
这个我写的一个函数（写在了一个公共函数的js文件里），我想在异步时的then（）函数里请求成功时发送action，如上，但提示dispatch未定义，请问我怎么把dispatch弄进来

**Comment by javaLuo** [comment]
如果你要这样export出去的话。

`
// 在页面的顶部引入两个东西：
import { bindActionCreators } from 'redux';
import { editProblem} from '../../a_action/app-action';

// 页面的底部这样写
export default connect(
    (state) => ({
    }), 
    (dispatch) => ({
        actions: bindActionCreators({ editProblem}, dispatch),
    }),
)(TestPageContainer);
`

**Comment by wangjunwei910208** [comment]
好的  谢谢！
