### ISSUE TITLE
有很多路由的时候，有什么简便的写法么？

### ISSUE THREAD

**Issue by zhans1993** [javaLuo/react-luo#37]
const Home = Loadable({
  loader: () => import(/* webpackChunkName:'home' */ '../home'),
  loading: Loading, // 自定义的Loading动画组件
  timeout: 10000, // 可以设置一个超时时间(s)来应对网络慢的情况（在Loading动画组件中可以配置error信息）
});
我这样写报加载错误
let [ Login  , Root] = [
    "../loginPage/index",
    "../root/index"
].map(item => {
    let component = Loadable({
        loader: () => import(`${item}`),
        loading: Loading, // 自定义的Loading动画组件
        timeout: 10000 // 可以设置一个超时时间(s)来应对网络慢的情况（在Loading动画组件中可以配置error信息）
    })
    return component
})

**Comment by zhans1993** [comment]
@javaLuo

**Comment by javaLuo** [comment]
```
()=> import(字符串)
```
异步import的参数只能是字符串，不能是变量<br/>
这是目前webpack的限制，没有办法完全动态编译<br/>
你写的这个方法本身很不错。但受限于webpack<br/>

Loadable插件提供了Loadable.Map() 并行加载多个模块，<br/>
但我试了一下，好像也不能很好的用于这种场景，不知道是不是我使用方法不对。
你可以看一下它的文档Loadable.Map部分：https://github.com/jamiebuilds/react-loadable#loadablemap

我再研究研究有没有什么好的办法
