### ISSUE TITLE
luo哥好，小弟再请教个问题，您方便的时候给解答下！

### ISSUE THREAD

**Issue by wangjunwei910208** [javaLuo/react-luo#4]
这个框架里面引入了ant design，我在使用的时候想换主题，但一直没有成功，请指教。万分感谢

**Comment by javaLuo** [comment]
额 还没弄过
我研究研究

**Comment by javaLuo** [comment]
我更新过代码了
4个文件有修改

**1** .babelrc
**2** paceage.json
**3** webpack.dev.config.js
**4** webpack.production.config.js

-------

**1** 你可以直接复制现在新的webpack.dev.config.js和webpack.production.config.js**
**2** .babelrc 中只是把`"style":"css"` 改为了 `“style”:true`
**3** package.json中添加了"theme"字段，可以在这个字段中根据antd的文档自定义主题。
也可以专门写个theme.js文件，然后package.json中的theme字段指向them.js文件的路径。

**Comment by wangjunwei910208** [comment]
谢谢  luo哥  已解决
