### ISSUE TITLE
开发ts版本

### ISSUE THREAD

**Issue by Dreamerryao** [javaLuo/react-luo#46]
看到这个基于最新技术维护的仓库很兴奋，内部样例代码也确实对新人会有很大帮助。
ts 目前已经稳定，我希望基于此仓库维护对应的ts版本，同时删除ui组件库依赖，因为我并不倡议在模版中限制ui库的使用
如果有需要，我也可以帮助完成对应ts版本的开发工作。

**Comment by javaLuo** [comment]
我非常赞同你的想法
不过在下TS用得不是很多，所以没有做TS版的。
我已邀请你成为该项目合作者，如果你有兴趣可以提交自己的代码或构建你自己的版本。
我非常欢迎和感谢。
