### ISSUE TITLE
求救！关于如何覆盖ant design的样式

### ISSUE THREAD

**Issue by wangjunwei910208** [javaLuo/react-luo#5]
luo哥好，我现在本地服务器跑项目的时候，为什么覆盖不了ant design的样式？
.ant-input-affix-wrapper .ant-input:not(:first-child) {
    padding-left: 24px;
}  这是ant design自带的
.login-box .ant-input-affix-wrapper .ant-input {
    padding-left: 30px;
}  这是我加的
但是一直覆盖不了上面的样式，总是上面的样式生效

**Comment by javaLuo** [comment]
你加个 !important 试一下呢
padding-left: 30px !important;

**Comment by wangjunwei910208** [comment]
可以 生效 ，麻烦luo哥了！
我想问能不能打包css的时候，先打包ant 的样式，然后再打包自己写的？

**Comment by javaLuo** [comment]
现在的配置是把所有的文件打包成1个app.js/app.css，vendors.js/vendors.css
如果配置异步加载（代码分割），就会生成很多js和css
配置异步加载可以在route/index.js中配置
