### ISSUE TITLE
关于项目构建的问题

### ISSUE THREAD

**Issue by zhans1993** [javaLuo/react-luo#6]
luo哥你好，我看工程项目只有开发环境运行，如果我要切换一下开发环境改怎么改呢？对这些还不大了解，还请赐教

**Comment by javaLuo** [comment]
暂时没有加打包后的文件运行环境
我稍后加一个
现在只能打包好了把build文件夹中的文件放到TomCat服务器，或者别的什么服务器，或者用express写一个Node.js服务来运行。

**Comment by javaLuo** [comment]
@zhans1993 
现在增加了 npm run dist 命令
1、npm run build   先构建最终代码
2、npm run dist    此命令会运行打包后的build文件夹下的最终代码。用的express写了一个简单服务

**Comment by zhans1993** [comment]
回复的很快速，我还想着呢，就恢复了，感谢！
