### ISSUE TITLE
是否添加日志模块呢

### ISSUE THREAD

**Issue by zhans1993** [javaLuo/react-luo#7]
罗哥，我看到目前项目里没有加日志模块，如果想添加日志模块是通过express的中间件还是redux 中间件来写呢，哪个更简单点呢

**Comment by javaLuo** [comment]
通过redux中间件吧，可以使用redux-logger
我在store/index.js中加了redux-logger, 简单配置了一下。

不过如果正式打包不需要的话，要手动取消。
用于生产环境的BUG日志记录有logrocket，国内的有Fundebug，属于第3方日志服务。
