### ISSUE TITLE
引入第三方js 的问题

### ISSUE THREAD

**Issue by zhans1993** [javaLuo/react-luo#8]
luo哥你好，请教一个问题，我之前的项目是通过 html 模板里面link 入一个第三方js ,那在这个工程里要怎么办呢？

**Comment by javaLuo** [comment]
可以直接在src/index.html中写<script src="..."></script>
一般常见的第3方JS库都有NPM包，可以搜索一下，然后npm install到项目里，这样比较正规。

**Comment by zhans1993** [comment]
我是使用  MD5    遇到一个问题，之前使用hex_md5（password） ，我在react  里面 import 进来发现对应不到方法,没找到对应的npm 包

**Comment by javaLuo** [comment]
额，有个md5-hex包，不知道行不行
我也没用过

**Comment by zhans1993** [comment]
刚用笨办法一个一个试过了，第一个 md5 就可以，还是谢谢指点

**Comment by zhans1993** [comment]
还有就是我直接在<script src="..."></script>这样引入的时候，一直报路径找不到的错误，路劲有什么要求吗
Uncaught SyntaxError: Unexpected token <

**Comment by javaLuo** [comment]
@zhans1993 
只能用绝对路径，第3方库引入的话可以用国内的CDN：http://www.bootcdn.cn/

**Comment by zhans1993** [comment]
哦哦，明白了，谢谢。

**Comment by zhans1993** [comment]
还是路径问题，我在src/assets/html2canvas.js 有js   
   例如src/index.html中写<script src="/src/assets/html2canvas,js"></script>   还是没有找到。。

**Comment by javaLuo** [comment]
@zhans1993 
可以直接使用这个CDN地址：
https://cdn.bootcss.com/html2canvas/0.5.0-beta4/html2canvas.min.js
或者 npm install html2canvas
html2canvas库有对应的npm包
