### ISSUE TITLE
linux 下生产压缩抱错

### ISSUE THREAD

**Issue by zhans1993** [javaLuo/react-luo#9]
luo哥，你好，我在ｗｉｎｄｏｗｓ　环境下打包代码就不报错，在ｌｉｎｕｘ　下打包就报下面这个错，这是什么原因呢？

ERROR in vendors.js from UglifyJs
Unexpected token: name (urlParts) [vendors.js:62274,4]

ERROR in vendors.js from UglifyJs
Unexpected token: name (urlParts) [vendors.js:62274,4]
Child html-webpack-plugin for "index.html":

**Comment by javaLuo** [comment]
是编译完了，运行的时候报错吗
等我弄个虚拟机看一下

**Comment by zhans1993** [comment]
不是运行抱错，是linux 下编译抱错

**Comment by zhans1993** [comment]
我找到原因了，是webpack-dev-server 的问题，我在包的说明文档找到了，这种写法支持到2.7.1

**Comment by javaLuo** [comment]
额 好吧
解决了就行
